version: '3.4'
services: 
    web:
        image: php_image:latest 
        container_name: phpStyle
        restart: always
        environment: 
            MYSQL_USER: "root"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "demo"
        volumes: 
            - ./code:/var/www/html/mydockerphp
        ports: 
            - 8002:80
            - 3307:3306